version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    env_file:
      - ./api/config/.env
    restart: unless-stopped
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: postgres
    volumes:
      - db_prod:/var/lib/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nskill
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - client
      - api
      - db
volumes:
  db_prod:
    external: true
